version: '2'

services:
  flask-wsgi:
    restart: always
    container_name: flask_test
    build:
      context: ./nginx-flask
      dockerfile: DockerFile
    image: nginx-flask
    volumes:
      - ./nginx-flask/webapp:/webapp
    ports:
      - "8088:80"
      - "4438:443"
    networks:
      - owncloud_default
    external_links:
      - mysql_5
    environment:
      MYSQL_DATABASE: "db_finance"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "zblj1211"
      MYSQL_HOST: "172.18.0.2"
      MYSQL_PORT: "3306"

networks:
    owncloud_default:
        external: true
